StringLiterals:
  Enabled: false

BlockComments:
  Enabled: false

HashEachMethods:
  Enabled: false

HashTransformKeys:
  Enabled: false

HashTransformValues:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

BlockDelimiters:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
